// 首页改版设计方案

// 创建 Figma 设计文件的示例脚本
console.log('=== 首页改版设计方案 ===');
console.log('');
console.log('## 设计概览');
console.log('');
console.log('### 整体布局调整');
console.log('1. **去掉服务项目区域**：完全移除原有的服务项目卡片，为裁教展示腾空间');
console.log('2. **优化轮播图区域**：增大轮播图尺寸，使用更有吸引力的台球主题图片');
console.log('3. **强化裁教展示**：');
console.log('   - 热门裁教区域：卡片尺寸增大30%，添加详细信息');
console.log('   - 新人推荐区域：增强视觉效果，添加优惠信息展示');
console.log('4. **保持深色主题**：使用 #121619 为主背景，#1E252B 为卡片背景');
console.log('');
console.log('### 热门裁教卡片设计');
console.log('');
console.log('```');
console.log('┌─────────────────────────────────┐');
console.log('│     [裁教头像]                  │');
console.log('│   [在线状态指示器] [评分] [等级] │');
console.log('├─────────────────────────────────┤');
console.log('│  [姓名]                         │');
console.log('│  [简介]                         │');
console.log('│  [已接单数]        [价格/小时] │');
console.log('└─────────────────────────────────┘');
console.log('```');
console.log('');
console.log('### 新人推荐卡片设计');
console.log('');
console.log('```');
console.log('┌─────────────────────────┐');
console.log('│   [渐变边框头像]       │');
console.log('│  [NEW标签] [在线状态]  │');
console.log('├─────────────────────────┤');
console.log('│    [姓名]               │');
console.log('│   [优惠信息]            │');
console.log('└─────────────────────────┘');
console.log('```');
console.log('');
console.log('### 配色方案');
console.log('');
console.log('| 用途 | 色值 |');
console.log('|------|------|');
console.log('| 主背景 | #121619 |');
console.log('| 卡片背景 | #1E252B |');
console.log('| 主按钮 | #00BB88 |');
console.log('| 次要按钮 | #3B82F6 |');
console.log('| 强调色 | #FFB800 |');
console.log('| 危险色 | #FF4D4F |');
console.log('');
console.log('### 响应式设计');
console.log('');
console.log('- **移动端**：单列布局，卡片宽度 100%');
console.log('- **平板端**：双列布局，卡片宽度 48%');
console.log('- **桌面端**：三列布局，卡片宽度 32%');
console.log('');
console.log('### 交互效果');
console.log('');
console.log('1. **卡片悬停效果**：轻微上浮，阴影增强');
console.log('2. **点击反馈**：缩放动画');
console.log('3. **轮播图**：自动轮播，触摸滑动');
console.log('4. **头像动画**：轻微旋转效果');